### ISSUE TITLE
Drop VarU64 encoding?

### ISSUE THREAD

**Issue by sbillig** [AljoschaMeyer/bamboo#10]
@AljoschaMeyer

This is very nitpicky, but is there a compelling reason to use VarU64 encoding (rather than, say, a big endian u64) for the numbers in the concatenated byte string?

Upside(s?): potentially matches the transmitted number format (though no transmission format is specified here)
Downsides: implementations need to support varu64 encoding, the byte string has dynamic length

**Comment by AljoschaMeyer** [comment]
Since I have declared bamboo to be stable and this would be a breaking change, I would have to reject this no matter whether I agreed with you or not.

The primary upside is that fewer bytes have to be signed (also hashed, but that should be negligible).

I don't consider the dynamic length of the byte string a particularly big downside, outside of signing operations you can always choose to use a different, fixed-size encoding. As for the additional complexity of having to support varu64: fair point, I was always planning to use bamboo in settings that also use varu64 in different places (networking in particular), so it would have been there anyways, and then it seemed weird to go for the slightly more expensive signature computations
